#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'Configuration' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Misc Termsyn 8" <<< "  Network|   Themes|   Bluetooth|   Sound")"
            case "$MENU" in
                *Network) nm-connection-editor;;
                *Themes) lxappearance;;
                *Bluetooth) systemctl reboot ;;
                *Sound) pavucontrol
            esac
